services:
  - type: web
    name: ElearningPlatform
    env: docker
    plan: free
    #    healthCheck:
    #      path: /actuator/health
    #      initialDelaySeconds: 45
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: defaultdb
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: defaultdb
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: defaultdb
          property: password